name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clone the SQLite Cloud docs repository
        run: git clone https://github.com/sqlitecloud/docs
        shell: bash
      - uses: ./
        with:
          project-string: ${{ secrets.PROJECT_STRING }}
          base-url: https://your-website.com/docs/
          database: docsearch-action-test.sqlite
          use-front-matter: true
          strip-md-titles: true
          strip-jsx: true
          strip-html: true
          path: docs
