name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          project-string: ${{ secrets.PROJECT_STRING }}
          database: documentation.sqlite
          remove-astro-headers: true
          remove-titles: true
